# Generated by Django 5.1.4 on 2025-01-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('certificate', models.FileField(default='', upload_to='certificates/%Y/%m/%d/')),
                ('password', models.CharField(max_length=100)),
                ('nsu', models.CharField(default='1', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
