# Generated by Django 5.1.4 on 2025-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AddField(
            model_name='business',
            name='uf',
            field=models.CharField(default='MG', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='business',
            name='certificate',
            field=models.FileField(default='', upload_to='certificates/%Y/%m/%d/', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='business',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='business',
            name='nsu',
            field=models.IntegerField(default='0', verbose_name='NSU'),
        ),
        migrations.AlterField(
            model_name='business',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Senha Certificado'),
        ),
    ]
