# Generated by Django 5.1.4 on 2025-01-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefaz', '0002_alter_business_options_business_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='uf',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('RR', 'Roraima'), ('RO', 'Rondônia'), ('TO', 'Tocantins'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('SE', 'Sergipe')], default='MG', max_length=2, verbose_name='UF'),
        ),
    ]
