# Generated by Django 5.1.4 on 2025-01-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiais',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ClassProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'classe de produto',
                'verbose_name_plural': 'classes de produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('typeEvent', models.CharField(max_length=30)),
                ('demonstrative', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['cod'],
            },
        ),
        migrations.CreateModel(
            name='FinancialClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grupo de eventos',
                'verbose_name_plural': 'grupos de eventos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['cnpj'],
            },
        ),
        migrations.CreateModel(
            name='TypeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de filial',
                'verbose_name_plural': 'tipos de filiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cooperators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('admission', models.DateField(verbose_name='Admissão')),
                ('ocupation', models.CharField(max_length=50, verbose_name='Cargo')),
                ('birthdate', models.DateField(verbose_name='Data de nascimento')),
                ('cod', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('link', models.IntegerField(unique=True, verbose_name='Vínculo')),
                ('type', models.CharField(max_length=30, verbose_name='Tipo de Contrato')),
                ('sex', models.CharField(max_length=30, null=True, verbose_name='Sexo')),
                ('demission', models.DateField(null=True, verbose_name='Demissão')),
                ('situation', models.CharField(max_length=30, verbose_name='Sitaução Funcional')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=30, null=True)),
                ('occurrence', models.DateField(null=True)),
                ('competence', models.DateField()),
                ('valuereference', models.FloatField()),
                ('value', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('cooperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.cooperators')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.events')),
            ],
            options={
                'verbose_name': 'histórico de evento',
                'verbose_name_plural': 'histórico de eventos',
                'ordering': ['competence', 'cooperator', 'event'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('period', models.CharField(max_length=7)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.branch')),
            ],
            options={
                'verbose_name': 'transação financeira',
                'verbose_name_plural': 'transações financeiras',
                'ordering': ['period', 'branch'],
            },
        ),
        migrations.CreateModel(
            name='EventsByGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.events')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.groupevents')),
            ],
            options={
                'verbose_name': 'evento por grupo',
                'verbose_name_plural': 'eventos por grupos',
                'ordering': ['group', 'event'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cod', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('unidade', models.CharField(max_length=4)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.classproduto')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_aprovacao', models.DateTimeField(null=True)),
                ('nr_solicitacao', models.CharField(max_length=10)),
                ('data_solicitacao', models.DateField()),
                ('qtd_itens', models.IntegerField()),
                ('justificativa', models.CharField(max_length=50)),
                ('status', models.CharField(default='AGUARDANDO', max_length=50)),
                ('inicio_atendimento', models.BooleanField(default=False)),
                ('dh_inicio_atendimento', models.DateTimeField(null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('dh_finalizada', models.DateTimeField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('branch_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_destino', to='billings.branch')),
                ('branch_solicitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_solicitacao', to='billings.branch')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador', to='billings.operador')),
                ('operador_atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador_atendimento', to='billings.operador')),
            ],
            options={
                'verbose_name': 'requisição',
                'verbose_name_plural': 'requisições',
                'ordering': ['data_solicitacao', 'branch_solicitacao', 'nr_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItensRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.FloatField()),
                ('dt_utiliza', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.produtos')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.requisicao')),
            ],
            options={
                'verbose_name': 'item de requisição',
                'verbose_name_plural': 'itens de requisições',
                'ordering': ['requisicao', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_id', models.CharField(max_length=12)),
                ('type', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('expiration', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.branch')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.supplier')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
                'ordering': ['launch_id'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.typebranch'),
        ),
    ]
