# Generated by Django 5.1.4 on 2025-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
