# Generated by Django 5.1.4 on 2025-01-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_alter_requisicao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.CharField(choices=[(1, 'AGUARDANDO'), (2, 'EM ATENDIMENTO'), (3, 'FINALIZADA')], default=1, max_length=1, verbose_name='STATUS'),
        ),
    ]
