# Generated by Django 5.1.4 on 2025-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_alter_requisicao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='classification',
            field=models.IntegerField(choices=[(1, 'INSUMO'), (2, 'EPI'), (3, 'OUTROS')], default=1, verbose_name='Classe'),
        ),
    ]
