# Generated by Django 5.1.4 on 2025-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0006_requisicao_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.IntegerField(choices=[(1, 'AGUARDANDO'), (2, 'EM ATENDIMENTO'), (3, 'FINALIZADA')], default=1, verbose_name='STATUS'),
        ),
    ]
