# Generated by Django 5.1.4 on 2025-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_alter_requisicao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='dh_finalizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
