# Generated by Django 5.1.4 on 2025-01-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_alter_requisicao_dh_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='dh_inicio_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
