# Generated by Django 5.1.4 on 2025-01-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0009_alter_requisicao_dh_inicio_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='operador_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador_atendimento', to='billings.operador'),
        ),
    ]
