# Generated by Django 5.1.4 on 2025-01-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_alter_requisicao_operador_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='progress',
            field=models.IntegerField(choices=[(1, 'NO PRAZO'), (2, 'PENDENTE'), (3, 'ATRASADO')], default=1, verbose_name='Progresso'),
        ),
    ]
