# Generated by Django 5.1.4 on 2025-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0011_requisicao_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='progress',
            field=models.IntegerField(choices=[(1, 'NO PRAZO'), (2, 'PENDENTE'), (3, 'ATRASADO'), (4, 'CONCLUIDO')], default=1, verbose_name='Progresso'),
        ),
    ]
