# Generated by Django 5.1.4 on 2025-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0012_alter_requisicao_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='tipo',
            field=models.CharField(choices=[(1, 'EXTRA EVENTO'), (2, 'ERRO DE PLANEJAMENTO'), (3, 'ERRO DE ESTOQUE'), (3, 'AUMENTO DE COMENSAIS')], default=1, max_length=25, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
