# Generated by Django 5.1.4 on 2025-05-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0013_requisicao_tipo_requisicao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'EXTRA EVENTO'), (2, 'ERRO DE PLANEJAMENTO'), (3, 'ERRO DE ESTOQUE'), (3, 'AUMENTO DE COMENSAIS')], default=1, max_length=25, verbose_name='Tipo'),
        ),
    ]
