# Generated by Django 5.1.4 on 2025-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0015_alter_requisicao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='valor',
            field=models.FloatField(blank=True, default=0, verbose_name='Valor'),
        ),
    ]
